from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_PATH = ROOT / "contracts" / "openapi.snapshot.json"
CLIENT_PATH = ROOT / "apps" / "web" / "src" / "api" / "generated" / "client.ts"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or check TypeScript API client.")
    parser.add_argument("--check", action="store_true", help="Fail if generated client is out of date.")
    args = parser.parse_args()

    snapshot = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    rendered = render_client(snapshot)
    if args.check:
        current = CLIENT_PATH.read_text(encoding="utf-8") if CLIENT_PATH.exists() else ""
        if current != rendered:
            print("apps/web/src/api/generated/client.ts is out of date", file=sys.stderr)
            return 1
        return 0

    CLIENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CLIENT_PATH.write_text(rendered, encoding="utf-8")
    return 0


def render_client(snapshot: dict[str, Any]) -> str:
    schemas = snapshot.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate_ts_client.py from contracts/openapi.snapshot.json.",
        "// Do not edit manually.",
        "",
        'export const API_BASE_PATH = "/api/v1";',
        "",
        "export type JsonValue =",
        "  | string",
        "  | number",
        "  | boolean",
        "  | null",
        "  | JsonValue[]",
        "  | { [key: string]: JsonValue };",
        "",
    ]
    for name in sorted(schemas):
        lines.extend(render_schema_type(name, schemas[name]))
        lines.append("")
    lines.extend(render_operations(snapshot))
    return "\n".join(lines).rstrip() + "\n"


def render_schema_type(name: str, schema: dict[str, Any]) -> list[str]:
    if "enum" in schema:
        values = " | ".join(json.dumps(value) for value in schema["enum"])
        return [f"export type {name} = {values};"]
    if schema.get("type") == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        if not properties and schema.get("additionalProperties") is True:
            return [f"export type {name} = Record<string, JsonValue>;"]
        lines = [f"export interface {name} {{"]
        for property_name in sorted(properties):
            optional = "" if property_name in required else "?"
            lines.append(
                f"  {json.dumps(property_name)}{optional}: {schema_to_ts(properties[property_name])};"
            )
        lines.append("}")
        return lines
    return [f"export type {name} = {schema_to_ts(schema)};"]


def render_operations(snapshot: dict[str, Any]) -> list[str]:
    operations = collect_operations(snapshot)
    lines = [
        "export type ApiPath =",
        *[f"  | {json.dumps(operation['path'])}" for operation in operations],
        "",
        "export type ApiMethod =",
        *[f"  | {json.dumps(operation['method'])}" for operation in operations],
        "",
        "export type ApiOperationId =",
        *[f"  | {json.dumps(operation['operation_id'])}" for operation in operations],
        "",
        "export const API_OPERATIONS = {",
    ]
    for operation in operations:
        lines.append(
            f"  {json.dumps(operation['operation_id'])}: "
            f"{{ method: {json.dumps(operation['method'])}, path: {json.dumps(operation['path'])} }},"
        )
    lines.extend(
        [
            "} as const;",
            "",
            "export type ApiRequestOptions<TBody = never> = {",
            "  path?: Record<string, string | number>;",
            "  query?: Record<string, string | number | boolean | null | undefined>;",
            "  headers?: Record<string, string>;",
            "  body?: TBody;",
            "  signal?: AbortSignal;",
            "};",
            "",
            "export class ApiClient {",
            '  constructor(private readonly baseUrl = "") {}',
            "",
        ]
    )
    for operation in operations:
        lines.extend(render_operation_method(operation))
        lines.append("")
    lines.extend(
        [
            "  private async request<TResponse, TBody = never>(",
            "    method: string,",
            "    pathTemplate: string,",
            "    options: ApiRequestOptions<TBody> = {},",
            "  ): Promise<TResponse> {",
            "    const response = await fetch(this.buildUrl(pathTemplate, options), {",
            "      method,",
            "      headers: {",
            '        ...(options.body === undefined ? {} : { "Content-Type": "application/json" }),',
            "        ...options.headers,",
            "      },",
            "      body: options.body === undefined ? undefined : JSON.stringify(options.body),",
            "      signal: options.signal,",
            "    });",
            "    if (!response.ok) {",
            "      throw new ApiClientError(response.status, await response.text());",
            "    }",
            "    if (response.status === 204) {",
            "      return undefined as TResponse;",
            "    }",
            "    return (await response.json()) as TResponse;",
            "  }",
            "",
            "  private buildUrl<TBody>(pathTemplate: string, options: ApiRequestOptions<TBody>): string {",
            "    let path = pathTemplate;",
            "    for (const [key, value] of Object.entries(options.path ?? {})) {",
            "      path = path.replace(`{${key}}`, encodeURIComponent(String(value)));",
            "    }",
            "    const url = new URL(`${this.baseUrl}${path}`, window.location.origin);",
            "    for (const [key, value] of Object.entries(options.query ?? {})) {",
            "      if (value !== undefined && value !== null) {",
            "        url.searchParams.set(key, String(value));",
            "      }",
            "    }",
            "    return url.toString();",
            "  }",
            "}",
            "",
            "export class ApiClientError extends Error {",
            "  constructor(",
            "    readonly status: number,",
            "    readonly responseText: string,",
            "  ) {",
            '    super(`API request failed with status ${status}`);',
            '    this.name = "ApiClientError";',
            "  }",
            "}",
        ]
    )
    return lines


def render_operation_method(operation: dict[str, str]) -> list[str]:
    request_type = operation["request_type"]
    response_type = operation["response_type"]
    body_type = request_type or "never"
    return [
        f"  async {operation['method_name']}(",
        f"    options: ApiRequestOptions<{body_type}> = {{}},",
        f"  ): Promise<{response_type}> {{",
        "    return this.request(",
        f"      {json.dumps(operation['method'])},",
        f"      {json.dumps(operation['path'])},",
        "      options,",
        "    );",
        "  }",
    ]


def collect_operations(snapshot: dict[str, Any]) -> list[dict[str, str]]:
    operations: list[dict[str, str]] = []
    for path, path_item in sorted(snapshot.get("paths", {}).items()):
        for method, operation in sorted(path_item.items()):
            if method.upper() not in {"GET", "POST", "PATCH", "PUT", "DELETE"}:
                continue
            operation_id = operation["operationId"]
            operations.append(
                {
                    "operation_id": operation_id,
                    "method_name": sanitize_identifier(operation_id),
                    "method": method.upper(),
                    "path": path,
                    "request_type": request_body_type(operation),
                    "response_type": response_type(operation),
                }
            )
    return operations


def request_body_type(operation: dict[str, Any]) -> str | None:
    schema = (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema")
    )
    return schema_to_ts(schema) if schema else None


def response_type(operation: dict[str, Any]) -> str:
    responses = operation.get("responses", {})
    for status in ("200", "201", "202"):
        schema = responses.get(status, {}).get("content", {}).get("application/json", {}).get("schema")
        if schema is not None:
            return schema_to_ts(schema)
    return "void"


def schema_to_ts(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "JsonValue"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", maxsplit=1)[-1]
    if "anyOf" in schema:
        return " | ".join(schema_to_ts(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    schema_type = schema.get("type")
    if schema_type == "array":
        return f"{schema_to_ts(schema.get('items'))}[]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Record<string, {schema_to_ts(additional)}>"
        return "Record<string, JsonValue>"
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    return "JsonValue"


def sanitize_identifier(value: str) -> str:
    identifier = re.sub(r"[^A-Za-z0-9_$]", "_", value)
    if not re.match(r"^[A-Za-z_$]", identifier):
        identifier = f"operation_{identifier}"
    return identifier


if __name__ == "__main__":
    raise SystemExit(main())
