from enum import StrEnum
from typing import TypeVar

TEnum = TypeVar("TEnum", bound=StrEnum)


class UnknownEnumValueError(ValueError):
    def __init__(self, enum_name: str, raw_value: object) -> None:
        self.enum_name = enum_name
        self.raw_value = raw_value
        super().__init__(f"Unknown {enum_name} value: {raw_value!r}")


class NodeType(StrEnum):
    AUTOMATED_SYSTEM = "AUTOMATED_SYSTEM"
    FUNCTIONAL_SUBSYSTEM = "FUNCTIONAL_SUBSYSTEM"
    MODULE = "MODULE"
    SUBMODULE = "SUBMODULE"
    MICROSERVICE = "MICROSERVICE"
    APPLICATION_COMPONENT = "APPLICATION_COMPONENT"
    INFRA_COMPONENT = "INFRA_COMPONENT"
    MESSAGE_BROKER = "MESSAGE_BROKER"
    TOPIC = "TOPIC"
    DATABASE = "DATABASE"
    EXTERNAL_SYSTEM = "EXTERNAL_SYSTEM"
    API_ENDPOINT = "API_ENDPOINT"
    UNKNOWN = "UNKNOWN"


class EdgeType(StrEnum):
    CONTAINS = "CONTAINS"
    SYNC_CALL = "SYNC_CALL"
    ASYNC_PUBLISH = "ASYNC_PUBLISH"
    ASYNC_SUBSCRIBE = "ASYNC_SUBSCRIBE"
    DATA_READ = "DATA_READ"
    DATA_WRITE = "DATA_WRITE"
    ROUTES_TO = "ROUTES_TO"
    DEPENDS_ON = "DEPENDS_ON"
    IMPLEMENTS = "IMPLEMENTS"
    UNKNOWN = "UNKNOWN"


class ValidationState(StrEnum):
    CONFIRMED = "CONFIRMED"
    CONFIRMED_WITH_WARNINGS = "CONFIRMED_WITH_WARNINGS"
    UNCONFIRMED = "UNCONFIRMED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECTED = "REJECTED"
    STALE = "STALE"


class AuditStatus(StrEnum):
    QUEUED = "QUEUED"
    SCANNING = "SCANNING"
    DISCOVERING = "DISCOVERING"
    ANALYZING = "ANALYZING"
    VALIDATING = "VALIDATING"
    ASSEMBLING = "ASSEMBLING"
    PARTIAL = "PARTIAL"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    INTERRUPTED = "INTERRUPTED"


class AuditStageName(StrEnum):
    PREFLIGHT = "PREFLIGHT"
    SCANNING = "SCANNING"
    UNIT_DETECTION = "UNIT_DETECTION"
    DISCOVERING = "DISCOVERING"
    ANALYZING = "ANALYZING"
    DETERMINISTIC_VALIDATION = "DETERMINISTIC_VALIDATION"
    LLM_VALIDATION = "LLM_VALIDATION"
    ASSEMBLING = "ASSEMBLING"
    SNAPSHOT_PERSISTENCE = "SNAPSHOT_PERSISTENCE"


TERMINAL_AUDIT_STATUSES = frozenset(
    {
        AuditStatus.COMPLETED,
        AuditStatus.COMPLETED_WITH_WARNINGS,
        AuditStatus.FAILED,
        AuditStatus.CANCELLED,
    }
)


class EntityOrigin(StrEnum):
    INFERRED = "INFERRED"
    MANUAL = "MANUAL"


class OverrideOperation(StrEnum):
    ADD_NODE = "ADD_NODE"
    UPDATE_NODE = "UPDATE_NODE"
    MOVE_NODE = "MOVE_NODE"
    SUPPRESS_NODE = "SUPPRESS_NODE"
    RESTORE_NODE = "RESTORE_NODE"
    ADD_EDGE = "ADD_EDGE"
    UPDATE_EDGE = "UPDATE_EDGE"
    SUPPRESS_EDGE = "SUPPRESS_EDGE"
    RESTORE_EDGE = "RESTORE_EDGE"


class GraphSnapshotStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"


class GraphRevisionStatus(StrEnum):
    DRAFT = "DRAFT"
    COMMITTED = "COMMITTED"


class GraphOverrideEntityKind(StrEnum):
    NODE = "NODE"
    EDGE = "EDGE"


class LlmValidatorDecision(StrEnum):
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    AMBIGUOUS = "AMBIGUOUS"
    INVALID_SEMANTICS = "INVALID_SEMANTICS"


class EvidenceStrength(StrEnum):
    STRONG = "STRONG"
    MEDIUM = "MEDIUM"
    WEAK = "WEAK"


class EvidenceSourceType(StrEnum):
    SOURCE_CODE = "SOURCE_CODE"
    MANIFEST = "MANIFEST"
    CONFIGURATION = "CONFIGURATION"
    DEPLOYMENT = "DEPLOYMENT"
    API_CONTRACT = "API_CONTRACT"
    DOCUMENTATION = "DOCUMENTATION"


class ReasonCode(StrEnum):
    INVALID_AUDIT_STATUS_TRANSITION = "INVALID_AUDIT_STATUS_TRANSITION"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    FAILED_SCHEMA = "FAILED_SCHEMA"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_INVALID = "EVIDENCE_INVALID"
    STALE_SOURCE = "STALE_SOURCE"
    REPOSITORY_CHANGED_DURING_AUDIT = "REPOSITORY_CHANGED_DURING_AUDIT"
    HARD_INVARIANT_VIOLATION = "HARD_INVARIANT_VIOLATION"
    INVALID_PARENT_TYPE = "INVALID_PARENT_TYPE"
    INVALID_EDGE_DIRECTION = "INVALID_EDGE_DIRECTION"
    CONTAINMENT_CYCLE = "CONTAINMENT_CYCLE"
    DUPLICATE_NODE = "DUPLICATE_NODE"
    DUPLICATE_EDGE = "DUPLICATE_EDGE"
    DUPLICATE_CANDIDATE = "DUPLICATE_CANDIDATE"
    SOURCE_TARGET_MISSING = "SOURCE_TARGET_MISSING"
    INSUFFICIENT_SOURCE_SIGNALS = "INSUFFICIENT_SOURCE_SIGNALS"
    NAMING_SIMILARITY_ONLY = "NAMING_SIMILARITY_ONLY"
    LLM_VALIDATOR_CONTRADICTED = "LLM_VALIDATOR_CONTRADICTED"
    LLM_VALIDATOR_INSUFFICIENT_EVIDENCE = "LLM_VALIDATOR_INSUFFICIENT_EVIDENCE"
    LLM_VALIDATOR_AMBIGUOUS = "LLM_VALIDATOR_AMBIGUOUS"
    LLM_VALIDATOR_INVALID_SEMANTICS = "LLM_VALIDATOR_INVALID_SEMANTICS"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


def parse_enum_value(enum_type: type[TEnum], raw_value: object) -> TEnum:
    try:
        return enum_type(raw_value)
    except ValueError as exc:
        raise UnknownEnumValueError(enum_type.__name__, raw_value) from exc
